---
- name: Web server setup
  hosts: all
  vars_files:
    - inventory/group_vars/all/vault.yml
    - roles/user_management/vars/main.yml
    -
  become: true
  roles:
    - user_management
    - ssh_config
    - zsh_setup
    - system_update
    - nginx_setup
    - deploy_static
    - zabbix
